0 = [
    "device_id",
    "counter",
    "latitude",
    "longitude",
    "altitude",
    "x1",
    "x2",
    "x3"
]
1 = [
    "device_id",
    "counter",
    "latitude",
    "longitude",
    "altitude",
    "x1",
    "x2",
    "x3"
]
