header = "BALLOON"
delimiter = ","
file_name = "team_a_b"
file_extension = "csv"
data_points = 120
state_key = "state"

[kml_keys.0]
lat = "latitude"
lon = "longitude"
alt = "altitude"

[kml_keys.1]
lat = "latitude"
lon = "longitude"
alt = "altitude"

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
0 = "counter"

[plot.y]
0 = [
    "altitude",
    "altitude_sec",
    "altitude_pht",
    "altitude_pht_ext"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
1 = "counter"

[plot.y]
1 = [
    "altitude",
    "altitude_sec",
    "altitude_pht",
    "altitude_pht_ext"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
0 = "counter"

[plot.y]
0 = [
    "humidity_pht",
    "humidity_pht_ext"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
1 = "counter"

[plot.y]
1 = [
    "humidity_pht",
    "humidity_pht_ext"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
0 = "counter"

[plot.y]
0 = [
    "temperature_pht",
    "temperature_pht_ext",
    "temperature_probe"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
1 = "counter"

[plot.y]
1 = [
    "temperature_pht",
    "temperature_pht_ext",
    "temperature_probe"
]

[[plot]]
plot_type = "xyz"
style = "line"

[plot.x]
0 = "counter"

[plot.y]
0 = "battery_volt"
1 = "battery_volt"

[state_name]
1 = "PRELAUNCH"
2 = "ASCENT"
3 = "HAVEN"
4 = "BREEZE"
5 = "BIND"
